<?php


/**
 * Implements hook_node_view()
 */
/*
function wiki9999_node_view($node) {
  // Wenn eine Node des Typs "topic" gespeichert wurde...
  if($node->type == 'opinion' || $node->type == 'proposal' || $node->type == 'standpoint') {
    dpm($node);
    // Wir speichern uns die Topic id in eine Variable.
    $topic_id = $node->field_topic_id_taxonomy[$node->language];
    // Wir speichern uns das Topic in eine Variable. http(s):// loeschen wir.
    $global_id = $topic_id . str_replace(array('https://', 'http://'), array('', ''), $GLOBALS['base_url'] ) . '/node/' . $node->nid . '-' . $node->type;

    $node_has_topic_id = FALSE;

    // Wenn die Node noch nicht das $topic als Term hat...
    if(!$node_has_topic_id) {
      // ... setzen wir manuell den Term in das Node-Objekt...
      $node->field_global_id[$node->language][0]['value'] = $global_id;
      ####$node->field_topic_id_taxonomy[$node->language][] = array('tid' => $saved_term->tid, 'taxonomy_term' => $saved_term);
      // ... und speichern die Node.
      #node_save($node);
    }

  }
}*/