<?php

/**
 * @file
 * Web service client - module file.
 */

/**
 * Implements hook_menu().
 */
function wsclient_menu() {
  $items['wsclient/%wsclient_service/notify'] = array(
    'page callback' => 'wsclient_notify',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'wsclient.inc',
  );
  return $items;
}

function wsclient_access($service) {
  return $service->access();
}

/**
 * Implements hook_entity_info().
 */
function wsclient_entity_info() {
  return array(
    'wsclient_service' => array(
      'label' => t('Web service description'),
      'entity class' => 'WSClientServiceDescription',
      'controller class' => 'EntityAPIControllerExportable',
      'base table' => 'wsclient_service',
      'module' => 'wsclient',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
        'name' => 'name',
        'label' => 'label',
      ),
      'exportable' => TRUE,
      'access callback' => 'wsclient_entity_access',
      'features controller class' => 'WSClientFeaturesController',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function wsclient_entity_info_alter(&$info) {
  $services = entity_load_multiple_by_name('wsclient_service', FALSE);
  // We register entities for all remote data types, however we skip the remote
  // site pointing at ourself ('self') defined by the testing module, as this
  // would result in issuing a page request during the entity info cache
  // refresh on our site, which would result in a nice cache building endless
  // loop.
  unset($services['self']);

  foreach ($services as $name => $service) {
    foreach ($service->entities() as $type => $type_info) {
      // Don't add in entity types, that stem from another site.
      if (strpos($type, 'wsclient_') !== 0) {
        $type_info += array('entity keys' => array(), 'label' => $type);
        $info['wsclient_' . $name . '_' . $type] = array(
          'label' => t('Web service %name %type', array('%name' => $service->label, '%type' => $type_info['label'])),
          'entity keys' => $type_info['entity keys'],
          'controller class' => 'WSClientServiceEntityController',
          'wsclient' => array(
            'remote' => $name,
            'type' => $type,
          ),
          'fieldable' => FALSE,
          'revision table' => FALSE,
        );
        foreach ($type_info['bundles'] as $bundle => $bundle_info) {
          $info['wsclient_' . $name . '_' . $type]['bundles'][$bundle] = array_intersect_key($bundle_info, array_flip(array('label')));
        }
        // Apply defaults as entity_get_info().
        $info['wsclient_' . $name . '_' . $type] += array(
          'static cache' => TRUE,
          'load hook' => 'wsclient_' . $name . '_' . $type . '_load',
          'view modes' => array(),
          'cacheable' => TRUE,
          'translation' => array(),
        );
      }
    }
  }
}

/**
 * Implements hook_entity_property_info().
 */
function wsclient_entity_property_info() {
  $info = array();
  foreach (entity_load_multiple_by_name('wsclient_service', FALSE) as $name => $service) {
    foreach ($service->entities() as $type => $type_info) {
      // Don't add in entity types, that stem from another site.
      if (strpos($type, 'wsclient_') !== 0) {
        $info['wsclient_' . $name . '_' . $type] = _wsclient_get_property_info($type_info);
        foreach ($type_info['bundles'] as $bundle => $bundle_info) {
          $info['wsclient_' . $name . '_' . $type]['bundles'][$bundle] = _wsclient_get_property_info($bundle_info);
        }
      }
    }
  }
  return $info;
}

function _wsclient_get_property_info($type_info) {
  $info = array_intersect_key($type_info, array_flip(array('properties')));
  if (!empty($info['properties'])) {
    foreach ($info['properties'] as &$property_info) {
      // Filter out only allowed keys.
      $property_info = array_intersect_key($property_info, array_flip(array('label', 'type', 'description', 'sanitize')));
      if (empty($property_info['type']) || $property_info['type'] == 'text') {
        // Make sure to sanitize text - don't trust given sanitize functions.
        $property_info += array('sanitize' => 'check_plain');
        if (!in_array($property_info['sanitize'], array('check_plain', 'filter_xss'))) {
          $property_info['sanitize'] = 'check_plain';
        }
      }
    }
  }
  return $info;
}

/**
 * Implements hook_permission().
 */
function wsclient_permission() {
  $permissions['administer web services'] = array(
    'title' => t('Administer web service descriptions'),
    'description' => t('Administer web service descriptions that can be used to connect to other sites.'),
  );
  foreach (entity_load_multiple_by_name('wsclient_service', FALSE) as $name => $service) {
    $permissions['interact with  ' . $name] = array(
      'title' => t('Interact with web service %label', array('%label' => $service->label)),
    );
  }
  return $permissions;
}

/**
 * Gets all defined remote endpoint types.
 */
function wsclient_get_types() {
  $data = array();
  foreach (module_implements('wsclient_endpoint_types') as $module) {
    $result = call_user_func($module . '_wsclient_endpoint_types');
    if (isset($result) && is_array($result)) {
      foreach ($result as $name => $item) {
        $item += array('module' => $module);
        $data[$name] = $item;
      }
    }
  }
  drupal_alter('wsclient_endpoint_types', $data);
  return $data;
}

/**
 * Load a single web service description.
 *
 * @return WSClientServiceDescription
 *   The web service description or FALSE.
 */
function wsclient_service_load($name) {
  $return = entity_load_multiple_by_name('wsclient_service', array($name));
  return reset($return);
}

/**
 * Gets configured http auth settings.
 */
function wsclient_get_http_auth() {
  if (($username = variable_get('wsclient_httpauth_username', NULL)) && $password = variable_get('wsclient_httpauth_password', NULL)) {
    return array(
      'method' => variable_get('wsclient_httpauth_method', CURLAUTH_BASIC),
      'username' => $username,
      'password' => $password,
    );
  }
}

/**
 * Implements hook_rules_event_set_alter().
 */
function wsclient_rules_event_set_alter($event_name, RulesEventSet $event_set) {
  // If a remote event is used make sure we are subscribed to it.
  if (strpos($event_name, 'wsclient_') === 0) {
    $info = $event_set->info();
    if (isset($info['wsclient']['remote']) && $service = wsclient_service_load($info['wsclient']['remote'])) {
      $event = $info['wsclient']['event'];
      if (!$service->isSubscribedTo($event)) {
        $service->subscribe($event);
      }
    }
  }
}

/**
 * Access callback for operations on wsclient entities.
 *
 * @see entity_access()
 */
function wsclient_entity_access($op, $entity, $account, $entity_type) {
  return user_access('administer web services', $account);
}

/**
 * Returns all data types of all services indexed by their global name.
 */
function wsclient_data_type_info() {
  $services = entity_load_multiple_by_name('wsclient_service');
  $types = array();
  foreach ($services as $name => $service) {
    foreach ($service->dataTypes() as $type_name => $info) {
      $types['wsclient_' . $name . '_' . $type_name] = $info;
    }
  }
  return $types;
}

/**
 * Maps the type name from the name used by the remote info to the rules name.
 */
function wsclient_map_type($service_name, $service_types, $type) {
  if (is_array($type)) {
    foreach ($type as $key => $entry) {
      $type[$key] = wsclient_map_type($service_name, $service_types, $entry);
    }
    return $type;
  }
  if (isset($service_types[$type])) {
    return 'wsclient_' . $service_name . '_' . $type;
  }
  if (strpos($type, 'list<') === 0 && isset($service_types[substr($type, 5, -1)])) {
    return 'list<wsclient_' . $service_name . '_' . substr($type, 5, -1) . '>';
  }
  return $type;
}
