<?php

/**
 * Implements hook_block_info().
 */
function wiki9999_feeds_block_info() {
  $blocks = array();

  // This block contains
  
   $blocks['connector_feeds'] = array(
    'info' => t('Connector Feeds'),
    'region' => 'sidebar_first',
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
  );
  
  return $blocks;
}



/**
  * Implements hook_block_view().
  */
function wiki9999_feeds_block_view($delta='') {
  $block = array();

  switch ($delta) {
      case 'connector_feeds':
      $block['title'] = t('All topics');
      $block['content'] = $block['content'] = connector_feeds_contents();
      break;
    
  }
  return $block;
}


/**
* custom html block
* @return string
*/
function connector_feeds_contents() {
  return '
      <ul>
        <li><a href="/all-topics/feed">Drupal default feed (xml)</a></li>
        <li><a href="/all-topics-of-a-website-in-xml">Views datasourc (xml)</a></li>
        <li><a href="/all-topics-of-a-website-in-json">Views datasource (json)</a></li>
        <li><a href="/all-topics-of-a-website-in-json">Views datasource (json)</a></li>
        <li><a href="/node/1.json">RESTful Web Services: JSON (just one node!)</a></li>
        <li><a href="/node/1.xml">RESTful Web Services: XML (just one node!)</a></li>
        <li><a href="/node/1.rdf">RESTful Web Services: RDF (just one node!)</a></li>
      </ul> 
  ';
}

?>